//go:build !ignore_autogenerated

package operator

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func (in *BrinecryptSecret) DeepCopyInto(out *BrinecryptSecret) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

func (in *BrinecryptSecret) DeepCopy() *BrinecryptSecret {
	if in == nil {
		return nil
	}
	out := new(BrinecryptSecret)
	in.DeepCopyInto(out)
	return out
}

func (in *BrinecryptSecret) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *BrinecryptSecretList) DeepCopyInto(out *BrinecryptSecretList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BrinecryptSecret, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *BrinecryptSecretList) DeepCopy() *BrinecryptSecretList {
	if in == nil {
		return nil
	}
	out := new(BrinecryptSecretList)
	in.DeepCopyInto(out)
	return out
}

func (in *BrinecryptSecretList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *BrinecryptSecretStatus) DeepCopyInto(out *BrinecryptSecretStatus) {
	*out = *in
	if in.LastSyncTime != nil {
		in, out := &in.LastSyncTime, &out.LastSyncTime
		*out = (*in).DeepCopy()
	}
}
