version: 1

repo:
  name: brinecrypt
  owner: RazzorCodes
  repo: brinecrypt

providers:
  github_actions:
    kind: github-actions
    owner: RazzorCodes
    repo: brinecrypt
    auth:
      token:
        secretRef:
          namespace: github
          name: coralforge-brinecrypt-repo-contents-rw-pat
          key: github_token

run_types:
  ci:
    default_provider: github_actions
    provider_target:
      workflow: ci.yml
    trigger:
      mode: manual
    stages:
      - name: ci
        provider: github_actions
        target:
          workflow: ci.yml
          job: ci
        runner: arc-runner-set

  release:
    default_provider: github_actions
    provider_target:
      workflow: release-tag.yml
    trigger:
      mode: manual
    stages:
      - name: release
        provider: github_actions
        target:
          workflow: release-tag.yml
          job: release
        runner: arc-runner-set
    depends_on: [ci]

  stable:
    default_provider: github_actions
    provider_target:
      workflow: release-stable.yml
    trigger:
      mode: manual
    stages:
      - name: stable
        provider: github_actions
        target:
          workflow: release-stable.yml
          job: stable
        runner: arc-runner-set
    depends_on: [release]
