{{- if .Values.ingress.enabled }}
{{- if not .Values.ingress.host }}{{ fail "values.ingress.host must be set when ingress.enabled=true" }}{{- end }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "brinecrypt.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "brinecrypt.labels" . | nindent 4 }}
spec:
  entryPoints:
    {{- toYaml .Values.ingress.entryPoints | nindent 4 }}
  routes:
    - match: Host(`{{ .Values.ingress.host }}`)
      kind: Rule
      {{- with .Values.ingress.middlewares }}
      middlewares:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      services:
        - name: {{ include "brinecrypt.fullname" . }}
          port: {{ .Values.service.port }}
  {{- with .Values.ingress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
