apiVersion: v1
kind: Secret
metadata:
  name: brinecrypt-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "brinecrypt.labels" . | nindent 4 }}
type: Opaque
stringData:
  database-url: {{ .Values.database.url | quote }}
  kek: {{ .Values.kek | quote }}
