apiVersion: brinekey.brinecrypt.io/v1alpha1
kind: BrinecryptSecret
metadata:
  name: brinekey-test
  namespace: test-ns
spec:
  remotePath: test-ns/test-rs
  serviceAccount: test-sa
  targetSecret: brinekey-test-secret
  secretKey: value
  refreshInterval: 1m
